(function(root){
'use strict';if(!root.React)return;
const h=React.createElement,C=CRMCommand,fmt=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n),unique=rs=>[...new Map(rs.map(r=>[r.key,r])).values()];

function actionProposals(records,model){const out=[],today=model.today;const add=(r,type,title,rationale,priority,key)=>out.push({record_kind:r.kind,record_id:r.id,action_type:type,title,rationale,priority,source:'rules',source_key:r.key+':'+key,payload:{}});for(const r of records){if(r.test||r.closed||r.command.linkedRecord)continue;const x=r.command||{};if(r.kind==='website_inquiries'&&r.raw.status==='New')add(r,'respond_inquiry','Respond to new website inquiry','A new booking inquiry is waiting for a response.',0,'new-inquiry');if(x.pricingRequested&&!x.pricingResponded)add(r,'send_pricing','Send requested pricing','Pricing was requested and is not marked answered.',1,'pricing-requested');if(r.followUp&&r.followUp<=today&&!r.booked)add(r,'follow_up',(r.followUp<today?'Overdue':'Today')+' follow-up','The recorded follow-up date is '+r.followUp+'.',r.followUp<today?1:2,'follow-up:'+r.followUp);if(r.stage==='Pricing / Proposal'&&!r.booked)add(r,'proposal_follow_up','Follow up on proposal','This opportunity is in Pricing / Proposal and is not booked.',3,'proposal:'+(x.proposalSentOn||'current'));if(r.booked){if(x.contractStatus!=='Signed')add(r,'complete_contract','Complete speaking contract','Booked engagement does not have a signed contract recorded.',3,'contract');if(r.payStatus!=='Received'&&x.paymentDue&&x.paymentDue<=today)add(r,'collect_payment','Collect outstanding payment','Payment is due '+x.paymentDue+' and is not marked received.',1,'payment:'+x.paymentDue);if(Number(x.depositAmount)>0&&!x.depositReceived)add(r,'collect_deposit','Collect deposit','A deposit is recorded but not marked received.',3,'deposit');if(!r.date)add(r,'set_event_date','Set booked engagement date','The engagement is booked without an event date.',2,'event-date');if(r.date&&r.date>=today&&r.date<=C.addDays(today,30)&&(!r.location||!r.audience||r.fee===null))add(r,'confirm_event','Confirm upcoming event details','The event is within 30 days and is missing location, audience, or fee details.',2,'confirm:'+r.date);if(r.date&&r.date<today&&(!x.testimonialRequested||!x.referralRequested))add(r,'post_event_follow_up','Request testimonial / referral','The event date has passed and post-event requests are incomplete.',4,'post-event:'+r.date);}else if(!r.followUp&&['Conversation','Replied','Contacted'].includes(r.stage)){const ds=[r.raw.contacted,...(r.log||[]).map(e=>e.date)].filter(C.validDate).sort(),latest=ds.pop();if(latest&&latest<C.addDays(today,-14))add(r,'restart_conversation','Restart inactive conversation','No follow-up is scheduled and recorded activity is more than 14 days old.',4,'restart:'+latest);}}return out;}
async function list(client,uid,table){let rows=[];for(let from=0;;from+=500){const q=await client.from(table).select('*').eq('user_id',uid).order(table==='crm_activity'?'occurred_at':'id',{ascending:false}).order('id').range(from,from+499);if(q.error)throw q.error;rows.push(...q.data);if(q.data.length<500)return rows;}}
function Editor({r,save,onClose,records}){
 const [x,setX]=React.useState({...r.command,market:r.market}),[fee,setFee]=React.useState(r.fee??''),[date,setDate]=React.useState(r.date),[status,setStatus]=React.useState(r.raw.status),[payment,setPayment]=React.useState(r.payStatus),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[dirty,setDirty]=React.useState(false);
 const set=(k,v)=>{setX(o=>({...o,[k]:v}));setDirty(true);};const values=(label,k,opts)=>h('label',null,label,h('select',{value:x[k]||'',onChange:e=>set(k,e.target.value)},['',...opts].map(v=>h('option',{key:v,value:v},v||'Not recorded'))));
 const field=(label,k,type='text')=>h('label',null,label,h('input',{type,value:x[k]??'',min:type==='number'?0:undefined,step:type==='number'?0.01:undefined,onChange:e=>set(k,e.target.value)}));const check=(label,k)=>h('label',{className:'cc-check'},h('input',{type:'checkbox',checked:!!x[k],onChange:e=>{set(k,e.target.checked);if(k==='qualified'&&e.target.checked&&!x.qualifiedOn)set('qualifiedOn',C.day(new Date()));}}),label);
 React.useEffect(()=>{window.crmCommandDirty=dirty;const fn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>{window.crmCommandDirty=false;window.removeEventListener('beforeunload',fn);};},[dirty]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await save(r,{...x,fee:fee===''?'':Number(fee),eventDate:date,paymentStatus:payment},status,fee,date,payment);setDirty(false);onClose();}catch(e){setError('Save failed. Edits retained. '+e.message);}finally{setBusy(false);}}
 return h('div',{className:'cc-editor'},h('div',{className:'cc-heading'},h('h2',null,r.name),h('button',{className:'btn',disabled:busy,onClick:()=>{if(!dirty||confirm('Discard unsaved opportunity changes?'))onClose();}},'Close')),
 h('p',null,'Opportunity details supplement the existing CRM record. Save here to update cloud data.'),h('form',{onSubmit:submit},h('div',{className:'cc-fields'},values('Market','market',[...C.markets,'Unclassified']),h('label',null,'Existing CRM status',h('select',{value:status,onChange:e=>{setStatus(e.target.value);setDirty(true);}},(r.kind==='website_inquiries'?CRMInquiries.statuses:['Not Started','Left Voicemail','Emailed','In Discussion','Booked!','Not Interested','Try Next Year']).map(s=>h('option',{key:s},s)))),values('Opportunity stage','stage',C.stages.filter(s=>s!=='Booked')),values('Lead source','source',['Direct outreach','Website','Google / SEO','Referral','Social media','Partner','Conference','Repeat client','Other']),check('Qualified prospect','qualified'),field('Qualified on','qualifiedOn','date'),field('Booked on (deal date)','bookedOn','date'),h('label',null,'Event date',h('input',{type:'date',value:date,onChange:e=>{setDate(e.target.value);setDirty(true);}})),h('label',null,'Speaking fee',h('input',{type:'number',min:0,step:0.01,value:fee,onChange:e=>{setFee(e.target.value);setDirty(true);}})),field('Event name','eventName'),field('Location','location'),field('Audience','audience'),field('Sales call date','callDate','date'),field('Proposal sent on','proposalSentOn','date'),check('Pricing requested','pricingRequested'),check('Pricing answered','pricingResponded')),
 h('details',null,h('summary',null,'Contract, payment and travel'),h('div',{className:'cc-fields'},values('Contract','contractStatus',['Needed','Sent','Signed']),field('Travel reimbursement','travelReimbursement','number'),field('Deposit amount','depositAmount','number'),check('Deposit received','depositReceived'),field('Amount received (total)','amountReceived','number'),field('Payment due','paymentDue','date'),h('label',null,'Payment status',h('select',{value:payment,onChange:e=>{setPayment(e.target.value);setDirty(true);}},['Not Invoiced','Invoiced','Received','Overdue'].map(v=>h('option',{key:v},v)))),values('Travel status','travelStatus',['Not needed','To arrange','Arranged']))),
 h('details',null,h('summary',null,'Conference opportunity'),h('div',{className:'cc-fields'},field('Conference name','conferenceName'),field('Organizer','organizer'),field('Website','website','url'),field('Conference contact','conferenceContact'),field('CFP deadline','cfpDeadline','date'),values('Opportunity type','opportunityType',['Keynote','Breakout','Workshop']),values('Submission status','submissionStatus',['Researching','Preparing','Submitted']),values('Decision','decisionStatus',['Pending','Accepted','Declined']),field('Potential fee','potentialFee','number'))),
 h('details',null,h('summary',null,'Partner / sponsor / referral relationship'),h('div',{className:'cc-fields'},values('Relationship type','relationshipType',['School-service company','Student leadership','Chamber','HR association','Event planner','Speaker bureau','Community organization','Sponsor','Referral partner']),field('Last contact','lastContact','date'),field('Next action','nextAction'),h('label',null,'Originating partner / sponsor',h('select',{value:x.partnerKey||'',onChange:e=>set('partnerKey',e.target.value)},h('option',{value:''},'None'),records.filter(v=>v.market==='Partners / Sponsors'&&v.key!==r.key).map(v=>h('option',{key:v.key,value:v.key},v.name)))),r.kind==='website_inquiries'&&h('label',null,'Linked existing prospect (exclude duplicate inquiry from totals)',h('select',{value:x.linkedRecord||'',onChange:e=>set('linkedRecord',e.target.value)},h('option',{value:''},'Independent inquiry'),records.filter(v=>v.kind!=='website_inquiries').map(v=>h('option',{key:v.key,value:v.key},v.name)))))),
 h('details',null,h('summary',null,'Post-event assets'),h('div',{className:'cc-fields'},...['testimonialRequested','testimonialReceived','photosReceived','videoReceived','mediaPermission','referralRequested'].map(k=>check(k.replace(/([A-Z])/g,' $1'),k)))),field('Opportunity notes','notes'),error&&h('p',{role:'alert'},error),h('button',{className:'btn primary',disabled:busy,type:'submit'},busy?'Saving…':'Save opportunity')));
}
root.SpeakingCommandCenter=function({contacts,client,uid,onOpenContact,onUpdateContact,onInquiries}){
 const [data,setData]=React.useState({inquiries:[],leads:[],activity:[]}),[actions,setActions]=React.useState([]),[loading,setLoading]=React.useState(true),[error,setError]=React.useState(''),[market,setMarket]=React.useState('All'),[period,setPeriod]=React.useState('All time'),[drill,setDrill]=React.useState(null),[editing,setEditing]=React.useState(null),[contentTitle,setContentTitle]=React.useState(''),[contentBusy,setContentBusy]=React.useState(false),[actionError,setActionError]=React.useState('');const request=React.useRef(0);
 async function refresh(){if(!uid){setLoading(false);return;}const ticket=++request.current;setLoading(true);try{const [inquiries,leads,activity]=await Promise.all([CRMInquiries.list(client,uid),list(client,uid,'leads'),list(client,uid,'crm_activity')]);if(ticket===request.current){setData({inquiries,leads,activity});const aq=await client.from('ai_actions').select('*').eq('user_id',uid).in('status',['pending','approved']).order('priority').order('created_at',{ascending:false});if(aq.error)throw aq.error;setActions(aq.data||[]);setError('');}}catch(e){if(ticket===request.current)setError('Command Center data could not be loaded. '+e.message);}finally{if(ticket===request.current)setLoading(false);}}
 React.useEffect(()=>{refresh();const timer=setInterval(refresh,60000);return()=>{request.current++;clearInterval(timer);};},[uid]);
 const records=[...contacts.map(c=>C.normalize(c)),...data.inquiries.map(c=>C.normalize(c,'website_inquiries')),...data.leads.map(c=>C.normalize({...c,school:c.name,command:c.command},'leads'))];const m=C.model(records,data.activity,new Date(),market,period);React.useEffect(()=>{if(!uid||loading||error)return;const wanted=actionProposals(records,m).map(a=>({...a,user_id:uid}));if(!wanted.length)return;client.from('ai_actions').upsert(wanted,{onConflict:'user_id,source_key',ignoreDuplicates:true}).then(({error:e})=>{if(e)setActionError('Recommendation sync failed. '+e.message);else client.from('ai_actions').select('*').eq('user_id',uid).in('status',['pending','approved']).order('priority').order('created_at',{ascending:false}).then(({data:d,error:le})=>{if(le)setActionError(le.message);else setActions(d||[]);});});},[uid,loading,data.inquiries.length,data.leads.length,data.activity.length,contacts.length]);
 const listRows=(title,rs)=>setDrill({title,keys:unique(rs).map(r=>r.key)});
 const row=(r,label)=>h('div',{className:'cc-record',key:r.key+(label||'')},h('button',{className:'cc-link',onClick:()=>r.kind==='progress'?onOpenContact(r.raw):setEditing(r)},h('strong',null,r.name),h('small',null,label||r.market+' · '+r.stage)),h('button',{className:'btn sm',onClick:()=>setEditing(r)},'Details'));
 async function save(r,command,status,fee,date,payStatus){
  if(['Booked!','Booked'].includes(status)&&!command.bookedOn&&!r.booked)command.bookedOn=m.today;
  if(r.kind==='progress'){onUpdateContact({...r.raw,command,status,fee:String(fee),gigDate:date,payStatus});if(window.crmPersistence){await new Promise(resolve=>setTimeout(resolve,0));if(!(await window.crmPersistence.flush()))throw Error('Cloud sync pending. Retry Cloud Save.');}}
  else {const changes=r.kind==='website_inquiries'?{command,status,booking_date:date||null}:{command,status};const q=await client.from(r.kind).update(changes).eq('user_id',uid).eq('id',r.id).select('*').single();if(q.error)throw q.error;if(!q.data)throw Error('Record not saved');}
  await refresh();
 }
 async function prepareAction(id){setActionError('');setActions(v=>v.map(a=>a.id===id?{...a,ai_status:'working'}:a));try{const q=await client.functions.invoke('prepare-ai-action',{body:{action_id:id}});if(q.error)throw q.error;if(!q.data?.action)throw Error(q.data?.message||'AI preparation did not return an action.');setActions(v=>v.map(a=>a.id===id?q.data.action:a));}catch(e){setActionError('AI preparation failed. '+(e.message||String(e)));await refresh();}}
 async function decideAction(id,status){setActionError('');const q=await client.from('ai_actions').update({status,decided_at:new Date().toISOString()}).eq('user_id',uid).eq('id',id).select('*').single();if(q.error){setActionError(q.error.message);return;}setActions(v=>v.map(a=>a.id===id?q.data:a).filter(a=>a.status!=='dismissed'));}
 async function executeAction(a,r){setActionError('');const o=a.ai_output||{},email=r&&(r.raw.email||(r.raw.record&&r.raw.record.email))||'';if(!email){setActionError('Cannot send: this CRM record has no email address.');return;}if(!confirm('Send this reviewed email to '+(r?.name||'this contact')+'?\\n\\nTo: '+email+'\\nSubject: '+(o.subject||'(no subject)')))return;setActions(v=>v.map(x=>x.id===a.id?{...x,execution_output:{state:'sending'}}:x));try{const q=await client.functions.invoke('execute-ai-action',{body:{action_id:a.id}});if(q.error)throw q.error;if(!q.data?.success)throw Error(q.data?.message||q.data?.error||'Email was not sent.');setActions(v=>v.filter(x=>x.id!==a.id));await refresh();}catch(e){setActionError('Send failed. '+(e.message||String(e)));await refresh();}}
 async function logContent(e){e.preventDefault();if(!contentTitle.trim()||contentBusy)return;setContentBusy(true);setActionError('');try{const q=await client.from('crm_activity').insert({user_id:uid,record_kind:'content',record_id:crypto.randomUUID(),event_type:'published',details:{title:contentTitle.trim()}});if(q.error)throw q.error;setContentTitle('');await refresh();}catch(e){setActionError(e.message);}finally{setContentBusy(false);}}
 const section=(title,children)=>h('section',{className:'dash-section cc-section'},h('h3',null,title),children);
 const table=(headers,rows)=>h('div',{className:'cc-table-wrap'},h('table',{className:'cc-table'},h('thead',null,h('tr',null,headers.map(v=>h('th',{key:v},v)))),h('tbody',null,rows)));
 const moneyCell=r=>r.fee===null?'Not recorded':fmt(r.fee);
 if(editing)return h('div',{className:'dash-wrap cc'},h(Editor,{key:editing.key,r:editing,records,save,onClose:()=>setEditing(null)}));
 const drillRecords=drill?records.filter(r=>drill.keys.includes(r.key)):[];
 const goals=[['qualified','New qualified prospects',50],['first','Personalized first contacts',45],['follow','Follow-ups',50],['partner','Partner / sponsor contacts',5],['conference','New conference opportunities',5],['content','Published content pieces',3]];
 const evidence=r=>C.evidence(r,data.activity);
 const funnel=market=>{const rs=m.selected.filter(r=>r.market===market);const sets=C.stages.map(stage=>rs.filter(r=>evidence(r).has(stage)));const rate=(a,b)=>{const denom=sets[a];if(!denom.length)return '—';const num=sets[b].filter(r=>denom.some(v=>v.key===r.key));return Math.round(num.length/denom.length*100)+'%';};return {rs,sets,rate};};
 const bookedByMonth={};for(const r of m.ytd){const month=m.bookingDate(r).slice(0,7);(bookedByMonth[month]||=[]).push(r);}
 return h('div',{className:'dash-wrap cc'},h('div',{className:'cc-heading'},h('div',null,h('h2',null,'Speaking Command Center'),h('p',null,'CLEAR: How We Respond Matters')),h('button',{className:'btn',onClick:refresh,disabled:loading},loading?'Refreshing…':'Refresh')),
 error&&h('p',{className:'inq-error',role:'alert'},error),h('div',{className:'cc-filters'},h('label',null,'Market',h('select',{value:market,onChange:e=>{setMarket(e.target.value);setDrill(null);}},['All',...C.markets].map(v=>h('option',{key:v},v)))),h('label',null,'Pipeline / funnel period',h('select',{value:period,onChange:e=>setPeriod(e.target.value)},['All time','Last 90 days','This year'].map(v=>h('option',{key:v},v))))),
 h('div',{className:'stat-grid'},[['Booked Revenue YTD',fmt(m.kpis.ytd),m.ytd,'By deal booking date'],['Next 90 Days',fmt(m.kpis.next90),m.upcoming.filter(r=>r.date<=C.addDays(m.today,90)),'Booked fees by event date'],['Open Pipeline Value',fmt(m.kpis.pipeline),m.pipeline,'Recorded fees; unweighted'],['Engagements Booked YTD',m.kpis.bookings,m.ytd,'By deal booking date']].map(([label,num,rs,sub])=>h('button',{className:'stat-card',key:label,onClick:()=>listRows(label,rs)},h('div',{className:'s-label'},label),h('div',{className:'s-num'},error||loading?'—':num),h('div',{className:'s-sub'},sub)))),
 (m.unknownFees||m.unknownBookingDates)>0&&h('p',{className:'cc-note'},m.unknownFees+' booked records missing a fee · '+m.unknownBookingDates+' missing a booking date. Totals exclude unknown values.'),
 section('This week · Monday '+m.start,h(React.Fragment,null,h('div',{className:'cc-goals'},goals.map(([k,label,target])=>h('button',{className:'cc-goal',key:k,onClick:()=>k==='content'?setDrill({title:'Published content',content:true,keys:[]}):listRows(label,m.weeklyRows[k]||[])},h('div',{className:'cc-heading'},h('span',null,label),h('strong',null,m.weekly[k]+' / '+target)),h('progress',{value:m.weekly[k],max:target,'aria-label':label}),h('small',null,m.weekly[k]>=target?'Target met':'Needs '+(target-m.weekly[k])+' more')))),h('div',{className:'cc-outcomes'},...['conversation','pricing','proposal','booking'].map(k=>h('button',{className:'btn',key:k,onClick:()=>listRows(k,m.weeklyRows[k]||[])},m.weekly[k]+' '+({conversation:'sales conversations',pricing:'pricing requests',proposal:'proposals sent',booking:'bookings'}[k])))),h('p',{className:'cc-note'},'Targets: 40–50 first contacts (45 shown), 50+ follow-ups. Confirmed sent-email logs count automatically. Queued emails do not count. Historical activity is retained. Content is logged after publishing.'),h('form',{className:'cc-content-form',onSubmit:logContent},h('input',{value:contentTitle,onChange:e=>setContentTitle(e.target.value),placeholder:'Title or URL of published content','aria-label':'Published content title',required:true}),h('button',{className:'btn',disabled:contentBusy},contentBusy?'Saving…':'Log published content')),actionError&&h('p',{role:'alert'},actionError))),
 section('Action queue · AI preparation',h(React.Fragment,null,h('p',{className:'cc-note'},'Recommendations come from recorded CRM facts. Prepare with AI creates a draft or analysis for your review. Approve only marks the item ready; it still does not send email or execute CRM changes.'),actions.length?h('div',{className:'cc-actions'},actions.slice(0,12).map(a=>{const r=records.find(v=>v.kind===a.record_kind&&v.id===a.record_id),o=a.ai_output||{};return h('div',{className:'cc-action '+(a.status==='approved'?'is-approved':''),key:a.id},h('div',{className:'cc-action-badge'},a.status+' · priority '+a.priority+' · AI '+(a.ai_status||'not_started')),h('strong',null,a.title),h('p',null,r?r.name:a.record_kind+' '+a.record_id),h('p',{className:'cc-note'},a.rationale),a.ai_status==='ready'&&h('div',{className:'cc-ai-output'},o.classification&&h('p',null,h('strong',null,'Classification: '),o.classification),o.summary&&h('p',null,h('strong',null,'Summary: '),o.summary),o.subject&&h('p',null,h('strong',null,'Subject: '),o.subject),o.draft&&h('div',null,h('strong',null,'Draft'),h('pre',{className:'cc-ai-draft'},o.draft)),o.recommended_next_step&&h('p',null,h('strong',null,'Recommended next step: '),o.recommended_next_step),Array.isArray(o.missing_information)&&o.missing_information.length>0&&h('p',null,h('strong',null,'Missing information: '),o.missing_information.join(', '))),a.ai_status==='failed'&&h('p',{role:'alert'},'AI preparation failed. '+(o.error||'Retry preparation.')),h('div',{className:'cc-action-buttons'},a.ai_status!=='working'&&h('button',{className:'btn',onClick:()=>prepareAction(a.id)},a.ai_status==='ready'?'Prepare again':'Prepare with AI'),a.ai_status==='working'&&h('button',{className:'btn',disabled:true},'Preparing…'),a.status==='pending'&&h('button',{className:'btn primary',disabled:a.ai_status!=='ready',title:a.ai_status==='ready'?'Mark this reviewed action approved':'Prepare with AI and review the result before approving',onClick:()=>a.ai_status==='ready'&&decideAction(a.id,'approved')},a.ai_status==='ready'?'Approve':'Prepare first'),h('button',{className:'btn',onClick:()=>decideAction(a.id,'dismissed')},'Dismiss'),r&&h('button',{className:'btn',onClick:()=>r.kind==='progress'?onOpenContact(r.raw):setEditing(r)},'Open record')));})):h('p',null,'No recommendations waiting.'))),
 section('Needs your attention',h(React.Fragment,null,error?h('p',null,'Website inquiries and supplemental records are unavailable. Retry refresh before relying on this list.'):null,m.alerts.length?h(React.Fragment,null,h('p',null,m.alerts.length+' next actions'),m.alerts.slice(0,10).map(a=>row(a.r,a.label)),m.alerts.length>10&&h('button',{className:'btn',onClick:()=>listRows('All records requiring attention',m.alerts.map(a=>a.r))},'View all attention records')):h('p',null,'No recorded urgent actions. Choose qualified prospects and make your next first contact.'))),
 drill&&section(drill.title,h(React.Fragment,null,h('button',{className:'btn',onClick:()=>setDrill(null)},'Close list'),drill.content?data.activity.filter(e=>e.record_kind==='content'&&C.day(new Date(e.occurred_at))>=m.start).map(e=>h('p',{key:e.id},e.details.title+' · '+C.day(new Date(e.occurred_at)))):drillRecords.length?drillRecords.map(r=>row(r)):h('p',null,'No matching recorded activity.'))),
 section('Sales pipeline',h(React.Fragment,null,h('div',{className:'cc-pipeline'},C.stages.map(stage=>{const rs=m.selected.filter(r=>r.stage===stage);return h('button',{className:'cc-stage',key:stage,onClick:()=>listRows(stage,rs)},h('strong',null,stage),h('b',null,rs.length),h('small',null,fmt(m.sum(rs))));})),h('p',{className:'cc-note'},'Current stage counts. Existing statuses remain intact: Emailed / Left Voicemail → Contacted; In Discussion → Conversation; Quote Sent → Pricing / Proposal. Reply and proposal stages use explicit evidence; later stages do not imply earlier ones. Period filters select records created or active during that period.'))),
 section('Market performance · recorded evidence',table(['Market','Prospects','Contacts','Replies','Conversations','Proposals','Bookings','Contact → Reply','Reply → Conversation','Conversation → Proposal','Proposal → Booking','Contact → Booking'],C.markets.map(v=>{const f=funnel(v);return h('tr',{key:v},h('td',null,h('button',{className:'cc-link',onClick:()=>{setMarket(v);listRows(v,f.rs);}},v)),h('td',null,f.rs.length),...f.sets.slice(1).map((rs,i)=>h('td',{key:i},h('button',{className:'cc-link',onClick:()=>listRows(v+' · '+C.stages[i+1],rs)},rs.length))),...[f.rate(1,2),f.rate(2,3),f.rate(3,4),f.rate(4,5),f.rate(1,5)].map((rate,i)=>h('td',{key:'r'+i},rate)));}))),
 section('Revenue visibility',h(React.Fragment,null,h('p',null,'Outstanding proposal value '+fmt(m.sum(m.proposals))+' · Average known booked fee '+(m.booked.some(r=>r.fee!==null)?fmt(m.sum(m.booked)/m.booked.filter(r=>r.fee!==null).length):'Not recorded')+' · Website inquiries this month '+data.inquiries.filter(r=>!C.normalize(r,'website_inquiries').test&&r.created_at.slice(0,7)===m.today.slice(0,7)).length),h('p',{className:'cc-note'},'Fees only; travel reimbursements are separate. Revenue means contracted fees, not cash received. Unknown fees are excluded.'),h('h4',null,'Booked revenue by month (deal date)'),Object.keys(bookedByMonth).length?table(['Month','Booked revenue'],Object.entries(bookedByMonth).sort().map(([k,rs])=>h('tr',{key:k},h('td',null,k),h('td',null,h('button',{className:'cc-link',onClick:()=>listRows(k,rs)},fmt(m.sum(rs))))))):h('p',null,'No bookings with a recorded deal date this year.'),h('h4',null,'Revenue by market · YTD'),table(['Market','Booked fees'],C.markets.map(v=>{const rs=m.ytd.filter(r=>r.market===v);return h('tr',{key:v},h('td',null,v),h('td',null,h('button',{className:'cc-link',onClick:()=>listRows(v+' revenue',rs)},fmt(m.sum(rs)))));})))),
 section('Upcoming speaking engagements',m.upcoming.length?m.upcoming.map(r=>row(r,r.date+' · '+(r.command.eventName||'Event name missing')+' · '+r.market+' · '+(r.command.location||r.location||'Location missing')+' · Audience '+(r.audience||r.command.audience||'missing')+' · '+moneyCell(r)+' · Contract '+(r.command.contractStatus||'missing')+' · '+r.payStatus+' · Travel '+(r.command.travelStatus||'missing')+' · Balance '+(r.fee===null?'unknown':fmt(Math.max(0,r.fee-(r.payStatus==='Received'?r.fee:C.money(r.command.amountReceived)||0)))))):h('p',null,'No booked engagements with upcoming event dates. Add a date and fee when a deal is confirmed.')),
 section('Revenue by speaking engagement',m.booked.length?m.booked.map(r=>row(r,(r.date||'Event date missing')+' · '+moneyCell(r)+' · '+r.payStatus)):h('p',null,'No booked speaking engagements recorded.')),
 section('Marketing attribution',table(['Source','Leads','Conversations','Bookings','Booked fees'],[...new Set(m.selected.map(r=>r.source))].sort().map(s=>{const rs=m.selected.filter(r=>r.source===s);return h('tr',{key:s},h('td',null,h('button',{className:'cc-link',onClick:()=>listRows(s,rs)},s)),h('td',null,rs.length),h('td',null,rs.filter(r=>evidence(r).has('Conversation')).length),h('td',null,rs.filter(r=>r.booked).length),h('td',null,fmt(m.sum(rs.filter(r=>r.booked)))));}))),
 section('Conference opportunities',m.scoped.filter(r=>r.market==='Conferences / Associations').length?m.scoped.filter(r=>r.market==='Conferences / Associations').map(r=>row(r,(r.command.cfpDeadline?'CFP '+r.command.cfpDeadline:'CFP deadline not recorded')+' · '+(r.command.submissionStatus||'Researching')+' · '+(r.command.decisionStatus||'Pending')+' · '+(r.command.opportunityType||'Type missing'))):h('p',null,'Add a prospect with the Conferences / Associations market. Track CFP deadlines and submission decisions in Details.')),
 section('Partners / sponsors',m.scoped.filter(r=>r.market==='Partners / Sponsors').length?m.scoped.filter(r=>r.market==='Partners / Sponsors').map(r=>{const influenced=records.filter(v=>!v.test&&!v.command.linkedRecord&&v.command.partnerKey===r.key);return row(r,(r.command.relationshipType||'Relationship type missing')+' · Last contact '+(r.command.lastContact||r.raw.contacted||'missing')+' · Next: '+(r.command.nextAction||'set next action')+' · '+influenced.length+' opportunities · '+influenced.filter(v=>v.booked).length+' bookings · '+fmt(m.sum(influenced.filter(v=>v.booked)))+' influenced');}):h('p',null,'Add a partner or sponsor using the existing prospect form. Link generated opportunities to that relationship in Details.')),
 h('p',{className:'cc-note'},'Calendar weeks and dashboard dates use America/Boise. Existing free-text logs do not establish historical replies or proposals. Mark explicit activity or opportunity stages as evidence becomes available. Closed integration tests are excluded from metrics.'),h('button',{className:'btn',onClick:onInquiries},'Open Website Inquiries'));
};
})(window);
